project:
  type: manuscript
  render: 
    - "index.qmd"
    - "!notes.qmd"

execute:
  freeze: auto
  cache: true

format:
  elsevier-pdf:
    includes:
      in_header: 'gt_packages.sty'
    journal:
      name: Journal Name
      formatting: preprint
      model: 1p
      cite-style: authoryear
    citeproc: false
    filters: 
      - at: pre-render
        path: "_extensions/andrewheiss/wordcount/citeproc.lua"
      - at: pre-render
        path: "_extensions/andrewheiss/wordcount/wordcount.lua"
