project:
  type: manuscript
  render: 
    - "index.qmd"
    - "!notes.qmd"

execute:
  freeze: false
  cache: true

format:
  elsevier-pdf:
    includes:
      in_header: 
        - 'gt_packages.sty'
    include-in-header:
      - text: |
          \usepackage[section]{placeins}
    journal:
      name: Journal Name
      formatting: preprint
      model: 1p
      cite-style: authoryear

