project:
  type: manuscript
  render: 
    - "index.qmd"
    - "!notes.qmd"

execute:
  freeze: auto
  cache: true

format:
  elsevier-pdf:
    keep-tex: true
    includes:
      in_header: 'gt_packages.sty'
    journal:
      name: Journal Name
      formatting: preprint
      model: 1p
      cite-style: authoryear



